apiVersion: v1
entries:
  sensitive-data:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2020-05-28T10:39:55.265350467Z"
    description: Sensitive-data is a service that searches for sensitive data in HTTP
      request/responses, both in headers and body.
    digest: 66d64f0388f65b35c68aee14cd1632b491076529d7c66e6a92bf8e28801707d2
    home: https://github.com/BBVA/apicheck
    maintainers:
    - email: security.group@bbva.com
      name: Innovation4security@bbva.com
      url: https://github.com/BBVA/apicheck
    name: sensitive-data
    sources:
    - https://github.com/BBVA/apicheck
    type: application
    urls:
    - sensitive-data-1.0.0.tgz
    version: 1.0.0
generated: "2020-05-28T10:39:55.26435037Z"
