apiVersion: v1
entries:
  sensitive-data:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2020-05-26T12:23:59.927863606Z"
    description: Sensitive-data is a service that searches for sensitive data in HTTP
      request/responses, both in headers and body.
    digest: ea46be4d756cda6b79ef39d34858ec225297f228a924475c741d1a12c69e9876
    home: https://github.com/BBVA/apicheck
    maintainers:
    - email: security.group@bbva.com
      name: Innovation4security@bbva.com
      url: https://github.com/BBVA/apicheck
    name: sensitive-data
    sources:
    - https://github.com/BBVA/apicheck
    type: application
    urls:
    - sensitive-data-1.0.0.tgz
    version: 1.0.0
generated: "2020-05-26T12:23:59.927315304Z"
