apiVersion: v1
entries:
  sensitive-data:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2020-05-28T05:49:22.898032338Z"
    description: Sensitive-data is a service that searches for sensitive data in HTTP
      request/responses, both in headers and body.
    digest: 352522c418d644e88f58cea5235cb2eff2a3d0dfc15bb0dd086660aaa7c02427
    home: https://github.com/BBVA/apicheck
    maintainers:
    - email: security.group@bbva.com
      name: Innovation4security@bbva.com
      url: https://github.com/BBVA/apicheck
    name: sensitive-data
    sources:
    - https://github.com/BBVA/apicheck
    type: application
    urls:
    - sensitive-data-1.0.0.tgz
    version: 1.0.0
generated: "2020-05-28T05:49:22.897495341Z"
