name: Build Docker Images

on:
  push:
    branches:
      - master
    paths:
      - "tools*/**/Dockerfile"
      - "tools*/**/META"
      - .github/workflows/build-docker-images.yml
      - build_docker_images.py


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3.0.1  # v2 does not have submodules option now

      - name: Build images
        run: python3 build_docker_images.py | sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
