name: github pages

on:
  push:
    branches:
      - master
    paths:
      - "helm/**"
      - "docs/**"
      - "tools/**/README.md"
      - "tools/**/META"
      - "tools-edge/**/README.md"
      - "tools-edge/**/META"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3.0.0  # v2 does not have submodules option now

      - name: Build Doc
        run: python3 build_doc.py

      - name: Build Helm charts
        run: ./build_helm_charts

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: false
          enable_jekyll: true
