name: github pages

on:
  push:
    branches:
      - master
    paths:
      - "docs/"
      - "tools/"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
#        with:
#          submodules: 'true'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.66.0'
          extended: true

      - name: Build Doc
        run: python build_doc.py

      - name: Build Site
        run: hugo -D --minify -d static -s docs/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/static
          keep_files: false