name: Build Pypi Artifacts

on:
  push:
    branches:
      - master
    paths:
      - "package-manager/apicheck_package_manager/__init__.py"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3.3.0  # v2 does not have submodules option now
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'

      - name: Build distribution package for Package Manager
        working-directory: ./package-manager
        run: |
          python3 -m pip install setuptools wheel
          python setup.py sdist bdist_wheel

      - name: Publish Package Manager to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.pypi_user }}
          password: ${{ secrets.pypi_password }}
          packages_dir: ./package-manager/dist/
